server {
    listen 80;
    server_name localhost;

    # Global Security Headers
    add_header Content-Security-Policy "default-src 'self' 'unsafe-inline' 'unsafe-eval' http://localhost:8080 http://localhost:8082; frame-ancestors 'none';" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Configure access and error logs to file for Fluent Bit collection
    access_log /var/log/nginx/aegis_access.log;
    error_log /var/log/nginx/aegis_error.log warn;

    # Maximum file upload size
    client_max_body_size 10M;

    # 1. Next.js Web Portal (FE_Web)
    location / {
        proxy_pass http://fe-web:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Security headers
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 2. Banking Spring Boot REST API (BE)
    # The trailing slash on proxy_pass strips the '/api-bank' prefix.
    # e.g., /api-bank/api/auth/login -> http://be-backend:8080/api/auth/login
    location /api-bank/ {
        proxy_pass http://be-backend:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. SOC Go Backend API (dashboard/backend)
    location /api/ {
        proxy_pass http://dashboard-backend:8082/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 4. SOC Dashboard React Frontend (dashboard/frontend)
    location /soc/ {
        proxy_pass http://dashboard-frontend:3001/soc/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 9000;
    server_name localhost;

    # Basic Auth to secure Kafdrop
    auth_basic "Secure Kafdrop Console";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
        proxy_pass http://kafka-ui:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
