[SERVICE]
    Flush        1
    Daemon       Off
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name             tail
    Path             /var/log/shared/aegis_access.log
    Tag              nginx.access
    Parser           nginx
    db               /var/log/shared/nginx-access.db
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[INPUT]
    Name             tail
    Path             /var/log/shared/aegis_error.log
    Tag              nginx.error
    db               /var/log/shared/nginx-error.db
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

[INPUT]
    Name             tail
    Path             /var/log/shared/application.log
    Tag              be.backend
    db               /var/log/shared/be-backend.db
    Mem_Buf_Limit    5MB
    Skip_Long_Lines  On

# ============================================
# Threat Detection Filters
# ============================================
[FILTER]
    Name    lua
    Match   nginx.access
    Script  filter_threats.lua
    Call    detect_threats

[FILTER]
    Name    lua
    Match   be.backend
    Script  filter_threats.lua
    Call    detect_threats

# Clones threat records to a new tag 'threat.alert'
[FILTER]
    Name          rewrite_tag
    Match         nginx.access
    Rule          $threat_detected ^true$ threat.alert true

[FILTER]
    Name          rewrite_tag
    Match         be.backend
    Rule          $threat_detected ^true$ threat.alert true

# ============================================
# Outputs
# ============================================
[OUTPUT]
    Name            stdout
    Match           *

[OUTPUT]
    Name            kafka
    Match           nginx.access
    Brokers         kafka-1:29092,kafka-2:29092,kafka-3:29092
    Topics          l0.input.apigw

[OUTPUT]
    Name            kafka
    Match           nginx.error
    Brokers         kafka-1:29092,kafka-2:29092,kafka-3:29092
    Topics          l0.input.waf

[OUTPUT]
    Name            kafka
    Match           be.backend
    Brokers         kafka-1:29092,kafka-2:29092,kafka-3:29092
    Topics          l0.input.ebanking-app

# Streams cloned threat alert records directly to the main Security Events topic
[OUTPUT]
    Name            kafka
    Match           threat.alert
    Brokers         kafka-1:29092,kafka-2:29092,kafka-3:29092
    Topics          aegis.security.events
    Format          json
